# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-project:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    machine:
      image: ubuntu-2204:2023.07.2
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install AWS CLI"
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: "Configure AWS CLI"
          command: |
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
            aws configure set region "$AWS_REGION"
      - run:
          name: "Clone adaptix"
          command: "git clone https://github.com/sakkke/adaptix.git"
      - run:
          name: "Build project"
          command: |
            cd adaptix
            sudo MIRROR=https://geo.mirror.pkgbuild.com PROFILE=.. ./build.sh
      - run:
          name: "Upload artifacts"
          command: "aws s3 cp adaptix/work/root.x86_64/archlive/out \"$S3_DEST\" --recursive"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-project-workflow:
    jobs:
      - build-project
